### ISSUE TITLE
Optimize speed

### ISSUE THREAD

**Issue by davidpomerenke** [SocialChangeLab/media-impact-monitor#106]
Optimize loading speed of the visualizations.

Approaches:
- [x] Caching in backend
- [ ] Reducing the amount of transferred data
  - [ ] filtering
  - [ ] versions with/without details, e.g. with/without descriptions for the protests
- [ ] Using compression (?)
- [x] Caching in frontend

**Comment by vogelino** [comment]
For sure! This might be very beneficial!
