### ISSUE TITLE
[VOG-322] Info Modal Functionality (Setup and Functionality, Not the Contents)

### ISSUE THREAD

**Issue by vogelino** [SocialChangeLab/media-impact-monitor#140]
Setup the functionality of the info modal that explains each chart in the interface. <br>This is not about finishing up the contents, but about making it easy to add them in the future.

<sub>[VOG-322](https://linear.app/vogelino/issue/VOG-322/info-modal-functionality-setup-and-functionality-not-the-contents)</sub>

**Comment by davidpomerenke** [comment]
How do we want this modal to look like, should it be similar to the individual protest pages?
If so, we need to consider #145 , which is already inside the individual protest page.
