### ISSUE TITLE
[VOG-331] Implement Synthetic Chart

### ISSUE THREAD

**Issue by vogelino** [SocialChangeLab/media-impact-monitor#149]
Design and implement a synthetic chart for display on the FAQ page and certain info modals.

<sub>[VOG-331](https://linear.app/vogelino/issue/VOG-331/implement-synthetic-chart)</sub>

**Comment by davidpomerenke** [comment]
synthetic chart [counterfactual chart] only works for average protests, not individual protests

only relevant for the methodology page, not the core pages

and arguably, the impact chart hover effect is already something like a synthetic chart? @kleinlennart @vogelino

**Comment by vogelino** [comment]
Understood! It's possible we do the synthetic chart as an hover, although I am not sure yet it this is UX-friendly (thinking hovering the hovered thing and if the mouse leaves everything closes, etc.) We need to think this through. But we'll find a way!
