### ISSUE TITLE
[VOG-332] Mentions Table UI (No real data yet)

### ISSUE THREAD

**Issue by vogelino** [SocialChangeLab/media-impact-monitor#150]
Create the component for the data table to later on display the mentions.<br>This is not about real data, it is about making sure the functionality works.

<sub>[VOG-332](https://linear.app/vogelino/issue/VOG-332/mentions-table-ui-no-real-data-yet)</sub>

**Comment by davidpomerenke** [comment]
There is now somewhat real data, that is actually from that timeframe and group, but not necessarily about the correct event.

**Comment by davidpomerenke** [comment]
see also #151

**Comment by vogelino** [comment]
@davidpomerenke I meant that this ticket was about building the UI component, independent of the real data. Not that it shouldn't contain real data :)
