### ISSUE TITLE
Accounts how?

### ISSUE THREAD

**Issue by davidpomerenke** [SocialChangeLab/media-impact-monitor#166]

**Comment by davidpomerenke** [comment]
@kleinlennart @vogelino 

probably out of scope

and do we still have a use case?

maybe we could have an "add your own data" page even without accounts, and for the start even without functionality and just some text and "email us to add your own data"

**Comment by vogelino** [comment]
@davidpomerenke I agree, let's let it in the backlog or remove it altogether. 👍
