### ISSUE TITLE
User feedback button

### ISSUE THREAD

**Issue by davidpomerenke** [SocialChangeLab/media-impact-monitor#181]
Add a button for user feedback using Sentry: https://social-change-lab.sentry.io/feedback/#feedback-sidequest

**Comment by davidpomerenke** [comment]
doesn't work with adblock enabled (at least not with my settings), but there's probably nothing we can do about that

**Comment by vogelino** [comment]
Unfortunately I don't See how. We would need  a custom domain to maybe escape AdBlock rules but I'm not sure this is possible. I'll have a look 👀
