### ISSUE TITLE
[ORG] API endpoint design

### ISSUE THREAD

**Issue by davidpomerenke** [SocialChangeLab/media-impact-monitor#36]
How do we structure the API, what parameters and outputs should it have?

**Comment by kleinlennart** [comment]
The way date parameters are currently implemented is not very consistent or logical.
Therefore, we should decide on:
- consistent defaults (e.g., set an `end_date` default to current date on the highest possible level)
  - generally, setting defaults in the Types seems arguably preferable compared to global scope vars in module scripts 
- consistent usage for all endpoints (where it makes sense)

**Comment by davidpomerenke** [comment]
We should determine the current date within the FastAPI routes in `api.py`, then it will always be the date of the request. Otherwise (if defined within global scope) it will be the date when the app has been started. Or we just set it in the frontend.

Having `request_date` as a parameter internally totally makes sense from a functional programming perspective, and especially with respect to caching. I wonder whether we also want to have it in the API. On the one hand, the REST philosophy implies (as I understand it) that a request always gives the same response. On the other hand, users may expect that the API always delivers data that is up to date.

I tend toward making it explicit in the API as well, and _not_ setting a default in the backend (due to the mentioned complication).

Maybe we can also call it `end_date` again, rather than `request_date`.

**Comment by vogelino** [comment]
I tend to agree with the fact that sending `start_date` and `end_date` in the request body should only return data for this range. I would be fine if the API would either require both the `start_date` and `end_date` and to error if `start_date` is provided and `end_date` is not. If none of those parameters are provided, it should return everything or a paginated result with sensible defaults. These are just some thoughts and I trust you guys with API design more that myself. :) Just let me know if anything changes. :)
