### ISSUE TITLE
[Design] FAQ page, explanation of each chart and their methods

### ISSUE THREAD

**Issue by vogelino** [SocialChangeLab/media-impact-monitor#81]
null

<sub>[VOG-255](https://linear.app/vogelino/issue/VOG-255/[design]-faq-page-explanation-of-each-chart-and-their-methods)</sub>

**Comment by kleinlennart** [comment]
I can have a go at the first write up of the FAQ and methods page

**Comment by davidpomerenke** [comment]
👍
